// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package step

import (
	"github.com/bitrise-io/go-xcode/v2/destination"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDeviceFinder creates a new instance of MockDeviceFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceFinder {
	mock := &MockDeviceFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeviceFinder is an autogenerated mock type for the DeviceFinder type
type MockDeviceFinder struct {
	mock.Mock
}

type MockDeviceFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceFinder) EXPECT() *MockDeviceFinder_Expecter {
	return &MockDeviceFinder_Expecter{mock: &_m.Mock}
}

// FindDevice provides a mock function for the type MockDeviceFinder
func (_mock *MockDeviceFinder) FindDevice(destination1 destination.Simulator) (destination.Device, error) {
	ret := _mock.Called(destination1)

	if len(ret) == 0 {
		panic("no return value specified for FindDevice")
	}

	var r0 destination.Device
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(destination.Simulator) (destination.Device, error)); ok {
		return returnFunc(destination1)
	}
	if returnFunc, ok := ret.Get(0).(func(destination.Simulator) destination.Device); ok {
		r0 = returnFunc(destination1)
	} else {
		r0 = ret.Get(0).(destination.Device)
	}
	if returnFunc, ok := ret.Get(1).(func(destination.Simulator) error); ok {
		r1 = returnFunc(destination1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceFinder_FindDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDevice'
type MockDeviceFinder_FindDevice_Call struct {
	*mock.Call
}

// FindDevice is a helper method to define mock.On call
//   - destination1 destination.Simulator
func (_e *MockDeviceFinder_Expecter) FindDevice(destination1 interface{}) *MockDeviceFinder_FindDevice_Call {
	return &MockDeviceFinder_FindDevice_Call{Call: _e.mock.On("FindDevice", destination1)}
}

func (_c *MockDeviceFinder_FindDevice_Call) Run(run func(destination1 destination.Simulator)) *MockDeviceFinder_FindDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 destination.Simulator
		if args[0] != nil {
			arg0 = args[0].(destination.Simulator)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDeviceFinder_FindDevice_Call) Return(device destination.Device, err error) *MockDeviceFinder_FindDevice_Call {
	_c.Call.Return(device, err)
	return _c
}

func (_c *MockDeviceFinder_FindDevice_Call) RunAndReturn(run func(destination1 destination.Simulator) (destination.Device, error)) *MockDeviceFinder_FindDevice_Call {
	_c.Call.Return(run)
	return _c
}

// ListDevices provides a mock function for the type MockDeviceFinder
func (_mock *MockDeviceFinder) ListDevices() (*destination.DeviceList, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListDevices")
	}

	var r0 *destination.DeviceList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*destination.DeviceList, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *destination.DeviceList); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*destination.DeviceList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeviceFinder_ListDevices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDevices'
type MockDeviceFinder_ListDevices_Call struct {
	*mock.Call
}

// ListDevices is a helper method to define mock.On call
func (_e *MockDeviceFinder_Expecter) ListDevices() *MockDeviceFinder_ListDevices_Call {
	return &MockDeviceFinder_ListDevices_Call{Call: _e.mock.On("ListDevices")}
}

func (_c *MockDeviceFinder_ListDevices_Call) Run(run func()) *MockDeviceFinder_ListDevices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeviceFinder_ListDevices_Call) Return(deviceList *destination.DeviceList, err error) *MockDeviceFinder_ListDevices_Call {
	_c.Call.Return(deviceList, err)
	return _c
}

func (_c *MockDeviceFinder_ListDevices_Call) RunAndReturn(run func() (*destination.DeviceList, error)) *MockDeviceFinder_ListDevices_Call {
	_c.Call.Return(run)
	return _c
}
