// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package step

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockRepository
func (_mock *MockRepository) Get(key string) string {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockRepository_Expecter) Get(key interface{}) *MockRepository_Get_Call {
	return &MockRepository_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockRepository_Get_Call) Run(run func(key string)) *MockRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Get_Call) Return(s string) *MockRepository_Get_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRepository_Get_Call) RunAndReturn(run func(key string) string) *MockRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockRepository_Expecter) List() *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockRepository_List_Call) Run(run func()) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(strings []string) *MockRepository_List_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func() []string) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockRepository
func (_mock *MockRepository) Set(key string, value string) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockRepository_Expecter) Set(key interface{}, value interface{}) *MockRepository_Set_Call {
	return &MockRepository_Set_Call{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockRepository_Set_Call) Run(run func(key string, value string)) *MockRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Set_Call) Return(err error) *MockRepository_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Set_Call) RunAndReturn(run func(key string, value string) error) *MockRepository_Set_Call {
	_c.Call.Return(run)
	return _c
}

// Unset provides a mock function for the type MockRepository
func (_mock *MockRepository) Unset(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Unset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Unset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unset'
type MockRepository_Unset_Call struct {
	*mock.Call
}

// Unset is a helper method to define mock.On call
//   - key string
func (_e *MockRepository_Expecter) Unset(key interface{}) *MockRepository_Unset_Call {
	return &MockRepository_Unset_Call{Call: _e.mock.On("Unset", key)}
}

func (_c *MockRepository_Unset_Call) Run(run func(key string)) *MockRepository_Unset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Unset_Call) Return(err error) *MockRepository_Unset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Unset_Call) RunAndReturn(run func(key string) error) *MockRepository_Unset_Call {
	_c.Call.Return(run)
	return _c
}
